version: 2.1
orbs:
    node: circleci/node@5.1.0
    coveralls: coveralls/coveralls@2.2.1
jobs:
    build_test_job:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run:
                command: yarn test
            - store_test_results:
                path: test_results
            - coveralls/upload
workflows:
    build_test_workflow:
        jobs:
            - build_test_job
