export default {
    GET_BRANDS: "GET_BRANDS",
    GET_BRANDS_FULFILLED: "GET_BRANDS_FULFILLED",
    POST_BRAND: "POST_BRAND",
    POST_BRAND_FULFILLED: "POST_BRAND_FULFILLED",
    PUT_BRAND: "PUT_BRAND",
    PUT_BRAND_FULFILLED: "PUT_BRAND_FULFILLED",
    GET_BRAND: "GET_BRAND",
    GET_BRAND_FULFILLED: "GET_BRAND_FULFILLED"
};
