export default {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORIES_FULFILLED: "GET_CATEGORIES_FULFILLED",
    GET_CATEGORIES_REJECTED: "GET_CATEGORIES_REJECTED",
    POST_CATEGORY: "POST_CATEGORY",
    POST_CATEGORY_FULFILLED: "POST_CATEGORY_FULFILLED",
    PUT_CATEGORY: "PUT_CATEGORY",
    PUT_CATEGORY_FULFILLED: "PUT_CATEGORY_FULFILLED",
    PUT_CATEGORY_REJECTED: "PUT_CATEGORY_REJECTED",
    GET_CATEGORY: "GET_CATEGORY",
    GET_CATEGORY_PENDING: "GET_CATEGORY_PENDING",
    GET_CATEGORY_FULFILLED: "GET_CATEGORY_FULFILLED",
    GET_CATEGORY_REJECTED: "GET_CATEGORY_REJECTED"
};
