export default {
    LOGIN: "LOGIN",
    LOGIN_FULFILLED: "LOGIN_FULFILLED",
    REGISTER: "REGISTER",
    REGISTER_FULFILLED: "REGISTER_FULFILLED",
    GET_PROFILE: "GET_PROFILE",
    GET_PROFILE_FULFILLED: "GET_PROFILE_FULFILLED",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    RESET_PASSWORD: "RESET_PASSWORD",
    DISCONNECT_PROVIDER: "DISCONNECT_PROVIDER",
    DISCONNECT_PROVIDER_FULFILLED: "DISCONNECT_PROVIDER_FULFILLED"
};
